export const SET_STATE = 'SET_STATE'

export const CHANGE_CLOCK_STYLE = 'CHANGE_CLOCK_STYLE'
export const CHANGE_CLOCK_TIMEZONE = 'CHANGE_CLOCK_TIMEZONE'
export const CHANGE_CLOCK_PRIMARY_COLOR = 'CHANGE_CLOCK_PRIMARY_COLOR'
export const CHANGE_CLOCK_SECONDARY_COLOR = 'CHANGE_CLOCK_SECONDARY_COLOR'
